all:
	pdflatex --shell-escape proj5.tex
	pdflatex --shell-escape proj5.tex 
zip:
	zip xzmitk01-fit.zip *.tex *.png Makefile

clean:
	rm -f proj5.{aux,dvi,log,out,pdf,ps,bcf,run.xml,bbl,blg,nav,snm,toc,pyg,vrb} xzmitk01-fit.zip
